### PR TITLE
Adding f# 4.1 Error handling via Result

### PR DESCRIPTION
**Pull request by wallymathieu**
- Moved main `Choice<,>` error handling to `Compatibility` modules
- Copy and modify of `Choice<,>` error handling but with `Result<,>`

### CODE REVIEW

**Comment by wallymathieu** [comment]
Thoughts @haf ?

**Comment by haf** [comment]
I don't think we need to break the API just to support Result. But I like supporting result.

**Comment by wallymathieu** [comment]
Perhaps creating a YoloResults.fs file? So that you can choose what kind of behavior you want?

**Comment by haf** [comment]
YoLo moves with f#, so if F# supports Result we can add it.

**Comment by wallymathieu** [comment]
So does this look more OK? Basically only adding the Result things and keeping everything else as is.

**Comment by haf** [comment]
Thanks!

**Comment by wallymathieu** [comment]
👍

**Pull request merged**
